format = """
$username\ 
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = 'red bold'
style_root = 'red bold'
format = '[\[](bold purple)[$user]($style)[@](bold green)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold blue)[\]](bold purple) '
disabled = false

[fill]
symbol = " "

[directory]
style = "bold yellow"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = ""
format = "[$symbol $branch]($style) "
style = "#f34f29"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false
added_style = 'bold green'
deleted_style = 'bold red'
format = '([+$added]($added_style))([-$deleted]($deleted_style) )'

[cmd_duration]
min_time = 0
disabled = false
show_milliseconds = true
style = 'bold yellow dimmed'
format='[$duration]($style)'
